/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De2_1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FormHangHoa extends javax.swing.JFrame {

    DefaultTableModel model;

    ArrayList<HangHoa> dshh = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHangHoa.class.getName());

    /**
     * Creates new form FormHangHoa
     */
    public FormHangHoa() {
        initComponents();
        model = (DefaultTableModel) tbl.getModel();
        setLocationRelativeTo(null);
    }

    private void valid(boolean condition, String msg) throws Exception {
        if (condition) {
            throw new Exception(msg);
        }
    }
    private void loadTable() {
        model.setRowCount(0);

        for (HangHoa hh : dshh) {
            if (hh instanceof DienThoai) {
                DienThoai dt = (DienThoai) hh;
                model.addRow(new Object[]{
                    dt.getMa(), dt.getTen(),
                    String.format("%,.2f", dt.getGiaN()),
                    String.format("%,.2f", dt.getGiaB()),
                    "Điện thoại",
                    String.format("%,.2f", dt.getGiaSim()),
                    null,
                    String.format("%,.2f", dt.loiNhuan())
                });
            } else if (hh instanceof MayTinhBang) {
                MayTinhBang mtb = (MayTinhBang) hh;
                model.addRow(new Object[]{
                    mtb.getMa(), mtb.getTen(),
                    String.format("%,.2f", mtb.getGiaN()),
                    String.format("%,.2f", mtb.getGiaB()),
                    "Máy tính bảng",
                    null,
                    mtb.getKtMan(),
                    String.format("%,.2f", mtb.loiNhuan())
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CÔNG CỤ QUẢN LÝ HÀNG HÓA");

        jButton1.setText("LẤY DỮ LIỆU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("TÌM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SẮP XẾP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("NHẬP MÃ HÀNG CẦN TÌM:");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ HÀNG", "TÊN HÀNG", "GIÁ NHẬP", "GIÁ BÁN", "LOẠI", "GIÁ SIM GHÉP", "KÍCH THƯỚC MÀN HÌNH (inch)", "LỢI NHUẬN"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dshh.clear();
        model.setRowCount(0);
        try (BufferedReader br = new BufferedReader(new FileReader("hanghoa.txt"))) {
            String line;
            int lineCount = 0;
            while ((line = br.readLine()) != null) {
                lineCount++;
                if (line.trim().isEmpty()) {
                    continue;
                }

                String p[] = line.split("\\$");
                valid(p.length < 6, "Dòng " + lineCount
                        + " trong file hanghoa.txt thiếu dữ liệu!");

                boolean loai = p[0].trim().equals("DT");
                String ma = p[1].trim();
                for(HangHoa hh : dshh){
                    valid(hh.getMa().equalsIgnoreCase(ma), "Mã trùng! Sửa lại mã ở dòng " + lineCount
                    + " trong file hanghoa.txt!");
                }
                String ten = p[2].trim();
                double giaN = Double.parseDouble(p[3].trim());
                double giaB = Double.parseDouble(p[4].trim());

                HangHoa hh;

                if (loai) {
                    double giaS = Double.parseDouble(p[5].trim());
                    hh = new DienThoai(giaS, ma, ten, giaN, giaB);

                } else {
                    double kt = Double.parseDouble(p[5].trim());
                    hh = new MayTinhBang(kt, ma, ten, giaN, giaB);
                }
                dshh.add(hh);
            }
            loadTable();
            JOptionPane.showMessageDialog(this, "Lấy dữ liệu thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            dshh.clear();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (dshh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống! Bấm nút \"LẤY DỮ LIỆU\" trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String ma = txtTim.getText().trim();

            valid(ma.isEmpty(), "Vui lòng nhập mã hàng cần tìm!");

            boolean found = false;
            for (HangHoa hh : dshh) {
                if (ma.equalsIgnoreCase(hh.getMa())) {
                    found = true;
                    JOptionPane.showMessageDialog(this, hh.toString());
                    break;
                }
            }
            valid(!found, "Không tìm thấy mã " + ma);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (dshh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống! Bấm nút \"LẤY DỮ LIỆU\" trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int i = 0; i < dshh.size() - 1; i++) {
            for (int j = 0; j < dshh.size() - i - 1; j++) {
                if (dshh.get(j).loiNhuan() < dshh.get(j + 1).loiNhuan()) {
                    HangHoa temp = dshh.get(j);
                    dshh.set(j, dshh.get(j + 1));
                    dshh.set(j + 1, temp);
                }
            }
        }
        loadTable();
        JOptionPane.showMessageDialog(this, "Đã sắp xếp!");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHangHoa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
