/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai3;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormSanPham extends javax.swing.JFrame {

    ArrayList<SanPham> dssp = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSanPham.class.getName());

    /**
     * Creates new form FormSanPham
     */
    public FormSanPham() {
        initComponents();
        setLocationRelativeTo(null);

        giaoDien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        cbLoai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        lbTim = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CÔNG CỤ QUẢN LÝ SẢN PHẨM");

        jLabel2.setText("MÃ SẢN PHẨM:");

        jLabel3.setText("TÊN SẢN PHẨM:");

        jLabel4.setText("GIÁ BÁN:");

        jLabel5.setText("LOẠI SẢN PHẨM:");

        lb1.setText("BẢO HÀNH (THÁNG)");

        lb2.setText("BẢO HÀNH (THÁNG)");

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHÍNH HÃNG", "XÁCH TAY" }));
        cbLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiItemStateChanged(evt);
            }
        });

        jButton1.setText("LẤY DỮ LIỆU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SẮP XẾP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("NHẬP MÃ SẢN PHẨM MUỐN TÌM (VD: sp1):");

        lbTim.setText("jLabel7");

        jButton3.setText("TÌM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("THÊM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(49, 49, 49)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMa))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim))
                    .addComponent(lbTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(lbTim)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void cbLoaiItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        // TODO add your handling code here:
        giaoDien();
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try (BufferedReader br = new BufferedReader(new FileReader("sanpham.txt"))) {
            String line;
            int lineCount = 0;
            dssp.clear(); // Xóa danh sách cũ trước khi load (tùy chọn)

            while ((line = br.readLine()) != null) {
                lineCount++;
                if (line.trim().isEmpty()) {
                    continue;
                }
                String[] p = line.split(",");
                if (p.length < 6) {
                    JOptionPane.showMessageDialog(this, "Dòng " + lineCount + " thiếu thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String loai = p[0].trim(), ma = p[1].trim(), ten = p[2].trim();
                String f1 = p[3].trim(), f2 = p[4].trim();
                double gia = Double.parseDouble(p[5].trim());

                if (loai.equalsIgnoreCase("CHÍNH HÃNG")) {
                    dssp.add(new SanPhamChinhHang(f1, Integer.parseInt(f2), ma, ten, gia));
                } else {
                    dssp.add(new SanPhamXachTay(f1, f2, ma, ten, gia));
                }
            }
            JOptionPane.showMessageDialog(this, "Lấy dữ liệu thành công!");
            dssp.forEach(System.out::println);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi đọc file: " + e.getMessage());
        }
    }                                        

// Hàm thực hiện Quick Sort
    private void quickSort(ArrayList<SanPham> list, int low, int high) {
        if (low < high) {
            int pi = partition(list, low, high);
            quickSort(list, low, pi - 1);
            quickSort(list, pi + 1, high);
        }
    }

// Hàm phân hoạch cho Quick Sort
    private int partition(ArrayList<SanPham> list, int low, int high) {
        double pivot = list.get(high).getGia(); // Chọn phần tử cuối làm chốt
        int i = (low - 1);

        for (int j = low; j < high; j++) {
            // Nếu phần tử hiện tại nhỏ hơn chốt (Sắp xếp tăng dần)
            if (list.get(j).getGia() < pivot) {
                i++;
                // Swap list[i] và list[j]
                SanPham temp = list.get(i);
                list.set(i, list.get(j));
                list.set(j, temp);
            }
        }
        // Swap list[i+1] và list[high] (chốt)
        SanPham temp = list.get(i + 1);
        list.set(i + 1, list.get(high));
        list.set(high, temp);

        return i + 1;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (dssp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống!");
            return;
        }
        //dssp.sort(Comparator.comparingDouble(SanPham::getGia));
        //quickSort(dssp, 0, dssp.size() - 1);
        int n = dssp.size();
        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (dssp.get(j).getGia() > dssp.get(j + 1).getGia()) {
                    SanPham temp = dssp.get(j);
                    dssp.set(j, dssp.get(j + 1));
                    dssp.set(j + 1, temp);
                }
            }
        }

        System.out.println("--- SAU KHI SẮP XẾP ---");
        dssp.forEach(System.out::println);
        JOptionPane.showMessageDialog(this, "Đã sắp xếp theo giá!");
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {
            String ma = txtMa.getText().trim(), ten = txtTen.getText().trim();
            String f1 = txt1.getText().trim(), f2 = txt2.getText().trim(), giaStr = txtGia.getText().trim();
            boolean isCH = "CHÍNH HÃNG".equals(cbLoai.getSelectedItem());

            valid(!ma.isEmpty() && !ten.isEmpty() && !giaStr.isEmpty() && !f1.isEmpty() && !f2.isEmpty(), "Vui lòng nhập đủ thông tin!");

            valid(!ten.matches(".*\\d.*"), "Tên sản phẩm không được chứa số!");
            if (isCH) {
                valid(!f1.matches(".*\\d.*"), "Nhà sản xuất không được chứa số!"); // Chỉ check NXS, Nguồn gốc có thể có số
            }
            for (SanPham sp : dssp) {
                valid(!sp.getMa().equalsIgnoreCase(ma), "Mã sản phẩm đã tồn tại!");
            }

            double gia = Double.parseDouble(giaStr);
            valid(gia > 0, "Giá bán phải lớn hơn 0!");

            SanPham sp;
            if (isCH) {
                int bh = Integer.parseInt(f2);
                valid(bh >= 0, "Thời gian bảo hành không được âm!");
                sp = new SanPhamChinhHang(f1, bh, ma, ten, gia);
            } else {
                sp = new SanPhamXachTay(f1, f2, ma, ten, gia);
            }

            dssp.add(sp);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá bán hoặc Bảo hành phải là số hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (dssp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống! Nhấn nút \"Lấy dữ liệu\" trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtTim.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sản phẩm cần tìm!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ma = txtTim.getText();
        boolean found = false;
        for (SanPham sp : dssp) {
            if (ma.equals(sp.getMa())) {
                found = true;
                lbTim.setText(sp.toString());
                return;
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có mã: " + ma);
        }
    }                                        

    private void giaoDien() {
        boolean isCH = "CHÍNH HÃNG".equals(cbLoai.getSelectedItem());
        lb1.setText(isCH ? "NHÀ SẢN XUẤT:" : "NGUỒN GỐC:");
        lb2.setText(isCH ? "BẢO HÀNH (THÁNG):" : "TÌNH TRẠNG:");
        lbTim.setText("");
    }

    private void valid(boolean condition, String msg) throws Exception {
        if (!condition) {
            throw new Exception(msg);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormSanPham().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbTim;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTim;
    // End of variables declaration                   
}
