/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai3;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormSanPham extends javax.swing.JFrame {

    ArrayList<SanPham> dssp = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSanPham.class.getName());

    /**
     * Creates new form FormSanPham
     */
    public FormSanPham() {
        initComponents();
        setLocationRelativeTo(null);

        giaoDien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        lbSP = new javax.swing.JLabel();
        cbLoai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSP = new javax.swing.JTextArea();
        JBUTTON = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CÔNG CỤ QUẢN LÝ SẢN PHẨM");

        jLabel2.setText("MÃ SẢN PHẨM:");

        jLabel3.setText("TÊN SẢN PHẨM:");

        jLabel4.setText("GIÁ BÁN:");

        jLabel5.setText("LOẠI SẢN PHẨM:");

        lb1.setText("NHÀ SẢN XUẤT:");

        lb2.setText("BẢO HÀNH (THÁNG):");

        lbSP.setText("THÔNG TIN SẢN PHẨM:");

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHÍNH HÃNG", "XÁCH TAY" }));
        cbLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiItemStateChanged(evt);
            }
        });

        taSP.setColumns(20);
        taSP.setRows(5);
        jScrollPane1.setViewportView(taSP);

        JBUTTON.setText("TÌM");
        JBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUTTONActionPerformed(evt);
            }
        });

        jButton2.setText("SẮP XẾP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("LẤY DỮ LIỆU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lb3.setText("Nhập mã sản phẩm cần tìm:");

        jButton3.setText("Lưu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3))
                    .addComponent(lbSP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBUTTON))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMa))
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTen))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtGia))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt2))))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb3)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUTTON))
                .addGap(18, 18, 18)
                .addComponent(lbSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiItemStateChanged
        // TODO add your handling code here:
        giaoDien();
    }//GEN-LAST:event_cbLoaiItemStateChanged

    private void showE(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dssp.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("sanpham.txt"))) {
            String line;
            int lineCount = 0;
            while ((line = br.readLine()) != null) {
                lineCount++;
                if (line.trim().isEmpty()) {
                    continue;
                }

                String p[] = line.split(",");
                if (p.length < 6) {
                    throw new Exception("Dòng " + lineCount + " thiếu thông tin:" + line);
                }

                String loai = p[0].trim();
                String ma = p[1].trim();
                String ten = p[2].trim();
                double gia = Double.parseDouble(p[5].trim());;
                if (loai.equals("CHÍNH HÃNG")) {
                    String nxs = p[3].trim();
                    int bh = Integer.parseInt(p[4].trim());;
                    dssp.add(new SanPhamChinhHang(nxs, bh, ma, ten, gia));
                } else {
                    String nguonGoc = p[3].trim();
                    String status = p[4].trim();
                    dssp.add(new SanPhamXachTay(nguonGoc, status, ma, ten, gia));
                }
            }
            JOptionPane.showMessageDialog(this, "Lấy dữ liệu thành công!");
        } catch (Exception e) {
            showE("Lỗi đọc file:" + e.getMessage());
            dssp.clear();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUTTONActionPerformed
        // TODO add your handling code here:
        if (dssp.isEmpty()) {
            showE("Danh sách rỗng!");
            return;
        }

        String ma = txtTim.getText().trim();
        if (ma.isEmpty()) {
            showE("Vui lòng nhập mã sản phẩm!");
            return;
        }

        boolean found = false;

        for (SanPham sp : dssp) {
            if (sp.getMaSP().equalsIgnoreCase(ma)) {
                found = true;
                taSP.setText(sp.toString());
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã hàng: " + ma);
        }
    }//GEN-LAST:event_JBUTTONActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (dssp.isEmpty()) {
            showE("Danh sách rỗng!");
            return;
        }

        dssp.sort((o1, o2) -> Double.compare(o1.getGia(), o2.getGia()));

        for (SanPham sp : dssp) {
            System.out.println(sp);
        }

        JOptionPane.showMessageDialog(this, "Đã sắp xếp xong!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (txtMa.getText().trim().isEmpty()
                || txtTen.getText().trim().isEmpty()
                || txtGia.getText().trim().isEmpty()
                || txt1.getText().trim().isEmpty()
                || txt2.getText().trim().isEmpty()) {
            showE("Vui lòng nhập đủ thông tin!");
            return;
        }

        try {
            String ma = txtMa.getText();
            String ten = txtTen.getText();
            String loai = cbLoai.getSelectedItem().toString();
            double gia = Double.parseDouble(txtGia.getText());
            
            for(SanPham sp : dssp){
                if(ma.equals(sp.getMaSP())){
                    showE("Mã sản phẩm đã tồn tại!");
                    return;
                }
            }
            
            if (loai.equals("CHÍNH HÃNG")) {
                String nxs = txt1.getText();
                int bh = Integer.parseInt(txt2.getText());
                dssp.add(new SanPhamChinhHang(nxs, bh, ma, ten, gia));
            } else {
                String nguonGoc = txt1.getText();
                String status = txt2.getText();
                dssp.add(new SanPhamXachTay(nguonGoc, status, ma, ten, gia));
            }
            
            JOptionPane.showMessageDialog(this, "Đã thêm vào danh sách!");
            txtMa.setText("");
            txtMa.requestFocus();
            txtTen.setText("");
            txtGia.setText("");
            txt1.setText("");
            txt2.setText("");
        } catch (NumberFormatException e) {
            showE("Giá bán/Bảo hành phải là số!");
        } catch (Exception e) {
            showE("Lỗi:" + e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void giaoDien() {
        String loai = cbLoai.getSelectedItem().toString();
        if (loai.equals("CHÍNH HÃNG")) {
            lb1.setText("NHÀ SẢN XUẤT:");
            lb2.setText("BẢO HÀNH (THÁNG):");
        } else {
            lb1.setText("NGUỒN GỐC:");
            lb2.setText("TÌNH TRẠNG:");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormSanPham().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUTTON;
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lbSP;
    private javax.swing.JTextArea taSP;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
