/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De3_2;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormRuong extends javax.swing.JFrame {

    ArrayList<Ruong> dsRuong = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRuong.class.getName());

    /**
     * Creates new form FormRuong
     */
    public FormRuong() {
        initComponents();
        setLocationRelativeTo(null);
        giaoDien();
    }

    private void giaoDien() {
        String loai = cbLoai.getSelectedItem().toString();
        if (loai.equals("Ruộng vuông")) {
            lbCanh1.setText("Độ dài cạnh:");
            lbCanh2.setVisible(false);
            txtCanh2.setVisible(false);
        } else {
            lbCanh1.setText("Chiều dài:");
            lbCanh2.setText("Chiều rộng:");
            lbCanh2.setVisible(true);
            txtCanh2.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCanh1 = new javax.swing.JTextField();
        lbCanh1 = new javax.swing.JLabel();
        lbCanh2 = new javax.swing.JLabel();
        txtCanh2 = new javax.swing.JTextField();
        cbLoai = new javax.swing.JComboBox<>();
        cbCay = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CÔNG CỤ QUẢN LÝ RUỘNG");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Mã ruộng:");

        jLabel8.setText("Tên chủ hộ:");

        jLabel9.setText("Loại cây trồng");

        jLabel10.setText("Loại ruộng:");

        lbCanh1.setText("Độ dài cạnh");

        lbCanh2.setText("Chiều rộng");

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruộng vuông", "Ruộng chữ nhật" }));
        cbLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiItemStateChanged(evt);
            }
        });

        cbCay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lúa", "ngô", "khoai" }));

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lưu File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Thống kê");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbCay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCanh1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCanh1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCanh2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCanh2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbCay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCanh1)
                    .addComponent(txtCanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCanh2)
                    .addComponent(txtCanh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiItemStateChanged
        // TODO add your handling code here:
        giaoDien();
    }//GEN-LAST:event_cbLoaiItemStateChanged

    private void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    private boolean checkTrungMa(String maMoi) {
        for (Ruong r : dsRuong) {
            if (r.getMaRuong().equalsIgnoreCase(maMoi)) {
                return true;
            }
        }
        return false;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String loai = cbLoai.getSelectedItem().toString();

        if (txtMa.getText().trim().isEmpty()
                || txtTen.getText().trim().isEmpty()
                || txtCanh1.getText().trim().isEmpty()
                || (loai.equals("Hình chữ nhật") && txtCanh2.getText().trim().isEmpty())) {
            showError("Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        String ma = txtMa.getText().trim();
        if (checkTrungMa(ma)) {
            showError("Mã ruộng " + ma + " đã tồn tại! Vui lòng nhập mã khác.");
            txtMa.requestFocus();
            return;
        }

        try {
            String ten = txtTen.getText();
            String cay = cbCay.getSelectedItem().toString();

            double canh1 = Double.parseDouble(txtCanh1.getText());

            Ruong r;

            if (loai.equals("Ruộng vuông")) {
                r = new RuongVuong(ma, ten, cay, canh1);
            } else {
                double canh2 = Double.parseDouble(txtCanh2.getText());
                r = new RuongChuNhat(ma, ten, cay, canh1, canh2);
            }

            dsRuong.add(r);
            JOptionPane.showMessageDialog(this, "Đã lưu vào danh sách!");

            txtMa.setText("");
            txtTen.setText("");
            txtCanh1.setText("");
            txtCanh2.setText("");
            txtMa.requestFocus();
            giaoDien();

        } catch (NumberFormatException e) {
            showError("Kích thước phải là số!!");
        } catch (Exception e) {
            showError("Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (dsRuong.isEmpty()) {
            showError("Danh sách rỗng!!");
            return;
        }

        int vuong = 0, chuNhat = 0, count = 0;
        Map<String, Integer> mapCay = new HashMap<>();

        for (Ruong r : dsRuong) {
            if (r instanceof RuongVuong) {
                vuong++;
            } else {
                chuNhat++;
            }

            if (r.tinhDienTich() > Ruong.DIEN_TICH_MAX) {
                count++;
            }

            String cay = r.getLoaiCayTrong();
            mapCay.put(cay, mapCay.getOrDefault(cay, 0) + 1);
        }

        int maxCount = 0;
        for (int soLuong : mapCay.values()) {
            if (soLuong > maxCount) {
                maxCount = soLuong;
            }
        }
        
        String cayMax = "";
        for(Map.Entry<String, Integer> entry : mapCay.entrySet()){
            if(entry.getValue() == maxCount){
                if(!cayMax.isEmpty()){
                    cayMax += ", ";
                }
                cayMax += entry.getKey();
            }
        }
        
        if(cayMax.isEmpty()){
            cayMax = "Không có";
        }

        String msg = "Số lượng ruộng vuông: " + vuong
                + "\nSố lượng ruộng chữ nhật: " + chuNhat
                + "\nLoại cây trồng nhiều nhất: " + cayMax
                + "\nSố ruộng lớn hơn diện tích tối đa (100m2): " + count;

        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (dsRuong.isEmpty()) {
            showError("Danh sách rỗng!!");
            return;
        }

        try (BufferedWriter bw = new BufferedWriter(new FileWriter("ruong.txt"))) {
            for (Ruong r : dsRuong) {
                bw.write(r.toString());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(this, "Ghi vào file ruong.txt thành công!");
        } catch (IOException e) {
            showError("Lỗi ghi file: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRuong().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCay;
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbCanh1;
    private javax.swing.JLabel lbCanh2;
    private javax.swing.JTextField txtCanh1;
    private javax.swing.JTextField txtCanh2;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
